
#include <iostream>
#include <time.h>
#include <conio.h>
#include<windows.h>
#include<stdlib.h>
void BlackjackCards1(int x)
{

	switch (x)
	{
	case 1:
		printf_s("========================== \n");
		printf_s("|   /\\                   | \n");
		printf_s("|  /  \\                 | \n");
		printf_s("| /----\\                | \n");
		printf_s("|/      \\              | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                \\      /| \n");
		printf_s("|                 \\____/ | \n");
		printf_s("|                  \\  /  | \n");
		printf_s("|                   \\/   | \n");
		printf_s("========================== \n");
		break;
	case 2:
		printf_s("========================== \n");
		printf_s("|   __                   | \n");
		printf_s("|  /  \\                  | \n");
		printf_s("|     |                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|  /___                  | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                  ___   | \n");
		printf_s("|                    /   | \n");
		printf_s("|                  /     | \n");
		printf_s("|                 |      | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 3:
		printf_s("========================== \n");
		printf_s("|  ---|                  | \n");
		printf_s("|  ---|                  | \n");
		printf_s("|  ___|                  | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                  |---  | \n");
		printf_s("|                  |---  | \n");
		printf_s("|                  |___  | \n");
		printf_s("========================== \n");
		break;
	case 4:
		printf_s("========================== \n");
		printf_s("|  |  |                  | \n");
		printf_s("|	 |__| 	               | \n");
		printf_s("|     |                  | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                  |     | \n");
		printf_s("|                  |--|  | \n");
		printf_s("|                  |  |  | \n");
		printf_s("========================== \n");
		break;
	case 5:
		printf_s("========================== \n");
		printf_s("|  __                    | \n");
		printf_s("|	|__    	               | \n");
		printf_s("|  __|                   | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                  __    | \n");
		printf_s("|                 |__    | \n");
		printf_s("|                    |   | \n");
		printf_s("|                  --    | \n");
		printf_s("========================== \n");
		break;
	case 6:
		printf_s("========================== \n");
		printf_s("|   |--                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("|   \\__/                 | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                   __|  | \n");
		printf_s("========================== \n");
		break;
	case 7:
		printf_s("========================== \n");
		printf_s("|   ___                  | \n");
		printf_s("|     /                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                   /    | \n");
		printf_s("|                  /     | \n");
		printf_s("|                  ---   | \n");
		printf_s("========================== \n");
		break;
	case 8:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  /  \\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 9:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  __/                   | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                   /--  | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 10:
		printf_s("========================== \n");
		printf_s("|  /| /-\\                | \n");
		printf_s("|   ||   |               | \n");
		printf_s("|   | \\_/                | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                 /-\\ |  | \n");
		printf_s("|                |   ||  | \n");
		printf_s("|                 \\_/ |/ | \n");
		printf_s("========================== \n");
		break;
	case 11:
		printf_s("========================== \n");
		printf_s("|    -|-                 | \n");
		printf_s("|     |                  | \n");
		printf_s("|  \\_/                  | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|                   /-\\  | \n");
		printf_s("|                   |    | \n");
		printf_s("|                  _|_   | \n");
		printf_s("========================== \n");
		break;
	case 12:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("| |   _|_                | \n");
		printf_s("|  \\__/  \\               | \n");
		printf_s("|                        | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                        | \n");
		printf_s("|               \\  /--\\  | \n");
		printf_s("|                -|-   | | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 13:
		printf_s("========================== \n");
		printf_s("|  | /                   | \n");
		printf_s("|  |/                    | \n");
		printf_s("|  |\\                    | \n");
		printf_s("|  | \\                   | \n");
		printf_s("|  /\\/\\                  | \n");
		printf_s("|  \\  /                  | \n");
		printf_s("|   \\/                   | \n");
		printf_s("|                        | \n");
		printf_s("|         /\\  /\\         | \n");
		printf_s("|         \\ \\/ /         | \n");
		printf_s("|          \\  /          | \n");
		printf_s("|           \\/           | \n");
		printf_s("|                        | \n");
		printf_s("|                   /\\   | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\/\\/  | \n");
		printf_s("|                   \\ |  | \n");
		printf_s("|                    \\|  | \n");
		printf_s("|                    /|  | \n");
		printf_s("|                   / |  | \n");
		printf_s("========================== \n");
		break;
	}
}
void BlackjackCards2(int x)
{

	switch (x)
	{
	case 1:
		printf_s("========================== \n");
		printf_s("|   /\\                   | \n");
		printf_s("|  /--\\                  | \n");
		printf_s("| /    \\                 | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                 \\    / | \n");
		printf_s("|                  \\--/  | \n");
		printf_s("|                   \\/   | \n");
		printf_s("========================== \n");
		break;
	case 2:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|  /___                  | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                 ---/   | \n");
		printf_s("|                  /     | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 3:
		printf_s("========================== \n");
		printf_s("|  ___                   | \n");
		printf_s("|  ___|                  | \n");
		printf_s("|  ___|                  | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                   ___  | \n");
		printf_s("|                  |___  | \n");
		printf_s("|                  |___  | \n");
		printf_s("========================== \n");
		break;
	case 4:
		printf_s("========================== \n");
		printf_s("|  |  |                  | \n");
		printf_s("|	 |__| 	               | \n");
		printf_s("|     |                  | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                  |     | \n");
		printf_s("|                  |--|  | \n");
		printf_s("|                  |  |  | \n");
		printf_s("========================== \n");
		break;
	case 5:
		printf_s("========================== \n");
		printf_s("|  __                    | \n");
		printf_s("|	|__    	               | \n");
		printf_s("|  __|                   | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                 |--    | \n");
		printf_s("|                  --|   | \n");
		printf_s("|                  --    | \n");
		printf_s("========================== \n");
		break;
	case 6:
		printf_s("========================== \n");
		printf_s("|   |--                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("|   \\__/                 | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                   __|  | \n");
		printf_s("========================== \n");
		break;
	case 7:
		printf_s("========================== \n");
		printf_s("|   ___                  | \n");
		printf_s("|     /                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                   /    | \n");
		printf_s("|                  /     | \n");
		printf_s("|                  ---   | \n");
		printf_s("========================== \n");
		break;
	case 8:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  /  \\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_     /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_    -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 9:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  __/                   | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                   /--  | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 10:
		printf_s("========================== \n");
		printf_s("|  /| /-\\                | \n");
		printf_s("|   ||   |               | \n");
		printf_s("|   | \\_/                | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                 /-\\ |  | \n");
		printf_s("|                |   ||  | \n");
		printf_s("|                 \\_/ |/ | \n");
		printf_s("========================== \n");
		break;
	case 11:
		printf_s("========================== \n");
		printf_s("|    -|-                 | \n");
		printf_s("|     |                  | \n");
		printf_s("|   \\_/                  | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                   /-\\  | \n");
		printf_s("|                   |    | \n");
		printf_s("|                  _|_   | \n");
		printf_s("========================== \n");
		break;
	case 12:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("| |   _|_                | \n");
		printf_s("|  \\__/  \\               | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_                  | \n");
		printf_s("|           /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_          | \n");
		printf_s("|                  -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|               \\  /--\\  | \n");
		printf_s("|                -|-   | | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 13:
		printf_s("========================== \n");
		printf_s("|  | /                   | \n");
		printf_s("|  |/                    | \n");
		printf_s("|  |\\                    | \n");
		printf_s("|  | \\                   | \n");
		printf_s("|   /-\\                  | \n");
		printf_s("|  /   \\                 | \n");
		printf_s("|  \\/|\\/                 | \n");
		printf_s("|   _|_     /-\\          | \n");
		printf_s("|          /   \\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|         \\     /        | \n");
		printf_s("|          \\/|\\/         | \n");
		printf_s("|           _|_    -|-   | \n");
		printf_s("|                 /\\|/\\  | \n");
		printf_s("|                 \\   /  | \n");
		printf_s("|                  \\_/   | \n");
		printf_s("|                   \\ |  | \n");
		printf_s("|                    \\|  | \n");
		printf_s("|                    /|  | \n");
		printf_s("|                   / |  | \n");
		printf_s("========================== \n");
		break;
	}
}
void BlackjackCards3(int x)
{

	switch (x)
	{
	case 1:
		printf_s("========================== \n");
		printf_s("|   /\\                   | \n");
		printf_s("|  /--\\                  | \n");
		printf_s("| /    \\                 | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                 \\    / | \n");
		printf_s("|                  \\--/  | \n");
		printf_s("|                   \\/   | \n");
		printf_s("========================== \n");
		break;
	case 2:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|  /___                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                 ---/   | \n");
		printf_s("|                  /     | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 3:
		printf_s("========================== \n");
		printf_s("|  ___                   | \n");
		printf_s("|  ___|                  | \n");
		printf_s("|  ___|                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                   ___  | \n");
		printf_s("|                  |___  | \n");
		printf_s("|                  |___  | \n");
		printf_s("========================== \n");
		break;
	case 4:
		printf_s("========================== \n");
		printf_s("|  |  |                  | \n");
		printf_s("|	 |__| 	               | \n");
		printf_s("|     |                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                  |     | \n");
		printf_s("|                  |--|  | \n");
		printf_s("|                  |  |  | \n");
		printf_s("========================== \n");
		break;
	case 5:
		printf_s("========================== \n");
		printf_s("|  __                    | \n");
		printf_s("|	|__    	               | \n");
		printf_s("|  __|                   | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                  __    | \n");
		printf_s("|                 |__    | \n");
		printf_s("|                  __|   | \n");
		printf_s("========================== \n");
		break;
	case 6:
		printf_s("========================== \n");
		printf_s("|   |--                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("|   \\__/                 | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                   __|  | \n");
		printf_s("========================== \n");
		break;
	case 7:
		printf_s("========================== \n");
		printf_s("|   ___                  | \n");
		printf_s("|     /                  | \n");
		printf_s("|    /                   | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                   /    | \n");
		printf_s("|                  /     | \n");
		printf_s("|                  ---   | \n");
		printf_s("========================== \n");
		break;
	case 8:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  /  \\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----   /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("|                  /  \\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 9:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("|  \\__/                  | \n");
		printf_s("|  __/                   | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                   /--  | \n");
		printf_s("|                  /--\\  | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 10:
		printf_s("========================== \n");
		printf_s("|  /| /-\\                | \n");
		printf_s("|   ||   |               | \n");
		printf_s("|   | \\_/                | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                 /-\\ |  | \n");
		printf_s("|                |   ||  | \n");
		printf_s("|                 \\_/ |/ | \n");
		printf_s("========================== \n");
		break;
	case 11:
		printf_s("========================== \n");
		printf_s("|    -|-                 | \n");
		printf_s("|     |                  | \n");
		printf_s("|   \\_/                  | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                   /-\\  | \n");
		printf_s("|                   |    | \n");
		printf_s("|                  _|_   | \n");
		printf_s("========================== \n");
		break;
	case 12:
		printf_s("========================== \n");
		printf_s("|  /--\\                  | \n");
		printf_s("| |   _|_                | \n");
		printf_s("|  \\__/  \\               | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----                 | \n");
		printf_s("|          /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|           |||          | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|               \\  /--\\  | \n");
		printf_s("|                -|-   | | \n");
		printf_s("|                  \\__/  | \n");
		printf_s("========================== \n");
		break;
	case 13:
		printf_s("========================== \n");
		printf_s("|  | /                   | \n");
		printf_s("|  |/                    | \n");
		printf_s("|  |\\                    | \n");
		printf_s("|  | \\                   | \n");
		printf_s("|   /--\\                 | \n");
		printf_s("| /-    -\\               | \n");
		printf_s("|  --||--                | \n");
		printf_s("|   ----   /---\\         | \n");
		printf_s("|         /     \\        | \n");
		printf_s("|      /--       --\\     | \n");
		printf_s("|      \\__       __/     | \n");
		printf_s("|         --|||--        | \n");
		printf_s("|         ------- ____   | \n");
		printf_s("|                __||__  | \n");
		printf_s("|               /_    _\\ | \n");
		printf_s("|                 \\__/   | \n");
		printf_s("|                   \\ |  | \n");
		printf_s("|                    \\|  | \n");
		printf_s("|                    /|  | \n");
		printf_s("|                   / |  | \n");
		printf_s("========================== \n");
		break;
	}
}
void BlackjackCards4(int x)
{

	switch (x)
	{
	case 1:
			printf_s("========================== \n");
			printf_s("|   /\\                   | \n");
			printf_s("|  /--\\                  | \n");
			printf_s("| /    \\                 | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                 \\    / | \n");
			printf_s("|                  \\--/  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("========================== \n");
			break;
		case 2:
			printf_s("========================== \n");
			printf_s("|  /--\\                  | \n");
			printf_s("|    /                   | \n");
			printf_s("|  /___                  | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                 ---/   | \n");
			printf_s("|                  /     | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("========================== \n");
			break;
		case 3:
			printf_s("========================== \n");
			printf_s("|  ___                   | \n");
			printf_s("|  ___|                  | \n");
			printf_s("|  ___|                  | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                   ___  | \n");
			printf_s("|                  |___  | \n");
			printf_s("|                  |___  | \n");
			printf_s("========================== \n");
			break;
		case 4:
			printf_s("========================== \n");
			printf_s("|  |  |                  | \n");
			printf_s("|  |__|                  | \n");
			printf_s("|     |                  | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                  |     | \n");
			printf_s("|                  |--|  | \n");
			printf_s("|                  |  |  | \n");
			printf_s("========================== \n");
			break;
		case 5:
			printf_s("========================== \n");
			printf_s("|  __                    | \n");
			printf_s("|	|__    	               | \n");
			printf_s("|  __|                   | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                  __    | \n");
			printf_s("|                 |__    | \n");
			printf_s("|                  __|   | \n");
			printf_s("========================== \n");
			break;
		case 6:
			printf_s("========================== \n");
			printf_s("|   |--                  | \n");
			printf_s("|   /--\\                 | \n");
			printf_s("|   \\__/                 | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                  /--\\  | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("|                   __|  | \n");
			printf_s("========================== \n");
			break;
		case 7:
			printf_s("========================== \n");
			printf_s("|   ___                  | \n");
			printf_s("|     /                  | \n");
			printf_s("|    /                   | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                   /    | \n");
			printf_s("|                  /     | \n");
			printf_s("|                  ---   | \n");
			printf_s("========================== \n");
			break;
		case 8:
			printf_s("========================== \n");
			printf_s("|  /--\\                  | \n");
			printf_s("|  \\__/                  | \n");
			printf_s("|  /  \\                  | \n");
			printf_s("|  \\__/                  | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/       /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/      /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                  /--\\  | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("========================== \n");
			break;
		case 9:
			printf_s("========================== \n");
			printf_s("|  /--\\                  | \n");
			printf_s("|  \\__/                  | \n");
			printf_s("|  __/                   | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                   /--  | \n");
			printf_s("|                  /--\\  | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("========================== \n");
			break;
		case 10:
			printf_s("========================== \n");
			printf_s("|  /| /-\\                | \n");
			printf_s("|   ||   |               | \n");
			printf_s("|   | \\_/                | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                 /-\\ |  | \n");
			printf_s("|                |   ||  | \n");
			printf_s("|                 \\_/ |/ | \n");
			printf_s("========================== \n");
			break;
		case 11:
			printf_s("========================== \n");
			printf_s("|    -|-                 | \n");
			printf_s("|     |                  | \n");
			printf_s("|   \\_/                  | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                   /-\\  | \n");
			printf_s("|                   |    | \n");
			printf_s("|                  _|_   | \n");
			printf_s("========================== \n");
			break;
		case 12:
			printf_s("========================== \n");
			printf_s("|  /--\\                  | \n");
			printf_s("| |   _|_                | \n");
			printf_s("|  \\__/  \\               | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/                    | \n");
			printf_s("|           /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/           | \n");
			printf_s("|                   /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|               \\  /--\\  | \n");
			printf_s("|                -|-   | | \n");
			printf_s("|                  \\__/  | \n");
			printf_s("========================== \n");
			break;
		case 13:
			printf_s("========================== \n");
			printf_s("|  | /                   | \n");
			printf_s("|  |/                    | \n");
			printf_s("|  |\\                    | \n");
			printf_s("|  | \\                   | \n");
			printf_s("|  /\\                    | \n");
			printf_s("| /  \\                   | \n");
			printf_s("| \\  /                   | \n");
			printf_s("|  \\/       /\\           | \n");
			printf_s("|          /  \\          | \n");
			printf_s("|         /    \\         | \n");
			printf_s("|         \\    /         | \n");
			printf_s("|          \\  /          | \n");
			printf_s("|           \\/      /\\   | \n");
			printf_s("|                  /  \\  | \n");
			printf_s("|                  \\  /  | \n");
			printf_s("|                   \\/   | \n");
			printf_s("|                   \\ |  | \n");
			printf_s("|                    \\|  | \n");
			printf_s("|                    /|  | \n");
			printf_s("|                   / |  | \n");
			printf_s("========================== \n");
			break;
		}
}
int BlackJack() {
	setlocale(LC_ALL, "ru");
	srand(time(NULL));
	int Igrok, Bot, i, bet, ballance, IgrokCard, BotCard, IgrokSum = 0, BotSum = 0,flag=0,flag1=0;
	printf_s("Введите балланс \n");
	scanf_s("%d", &ballance);
	do {
		printf_s("Выбирите действие \n1 --> Сделать ставку \n2 -->  получить свои карты \n3 --> Взять ещё карту \n4 --> карты бота  \n5 --> Узнать карты \n 6 --> выйти из игры \n");
		scanf_s("%d", &i);
		switch (i) {
		case 1:
			system("cls");
			printf_s("Введите сумму ставки --> ");
			do {
				scanf_s("%d", &bet);
				if (bet > ballance || bet < 0)
					printf_s("Ваша ставка некорректна ");
			} while (bet > ballance || bet <= 0);
			break;
		case 2:
			system("cls");
			for (int i = 0; i < 2; i++) {
				Igrok = rand() % 13 + 1;
				IgrokCard = rand() % 4 + 1;
				if (IgrokCard == 1)
					BlackjackCards1(Igrok);
				if (IgrokCard == 2)
					BlackjackCards2(Igrok);
				if (IgrokCard == 3)
					BlackjackCards3(Igrok);
				if (IgrokCard == 4)
					BlackjackCards4(Igrok);
				if (Igrok > 10)
					Igrok = 10;
				if (Igrok == 1)
				{
					Igrok = 11;
					flag ++ ;
				}
				IgrokSum += Igrok;
				if (Igrok == 1 && IgrokSum > 21)
					IgrokSum -= 10;
				Igrok = 0;
			}
			break;
		case 3:
			Igrok = rand() % 13 + 1;
			IgrokCard = rand() % 4 + 1;
			if (IgrokCard == 1)
				BlackjackCards1(Igrok);
			if (IgrokCard == 2)
				BlackjackCards2(Igrok);
			if (IgrokCard == 3)
				BlackjackCards3(Igrok);
			if (IgrokCard == 4)
				BlackjackCards4(Igrok);
			if ((Igrok == 1 && IgrokSum > 21) || (IgrokSum>21 && flag>0))
				IgrokSum -= 10;
			Igrok = 0;
			break;
		case 4:
			do {
				Bot = rand() % 13 + 1;
				BotCard = rand() % 4 + 1;
				if (BotCard == 1)
					BlackjackCards1(Bot);
				if (BotCard == 2)
					BlackjackCards2(Bot);
				if (BotCard == 3)
					BlackjackCards3(Bot);
				if (BotCard == 4)
					BlackjackCards4(Bot);
				if (Bot > 10)
					Bot = 10;
				if (Bot == 1)
				{
					Bot = 11;
					flag1++;
				}
				BotSum += Bot;
				if (Bot == 1 && BotSum > 21)
					BotSum -= 10;
				if ((Bot == 1 && BotSum > 21) || (BotSum > 21 && flag1 > 0))
					BotSum -= 10;
				Bot = 0;
			} while (BotSum < 16);
			break;
		case 5:
			system("cls");
			if ((IgrokSum > BotSum && IgrokSum <22) || BotSum>21 ) {
				ballance += bet;
				printf_s("Вы победили , держите свой выигрышь \n Ваш балланс --> %d ", ballance);
			}
			if ((IgrokSum < BotSum && BotSum < 22) || IgrokSum > 21) {
				ballance -= bet;
				printf_s(" Вы проиграли \n Ваш балланс --> %d ", ballance);
			}
			if (BotSum == IgrokSum) {
				printf_s("Ничья");
				printf_s(" Ваш балланс --> %d \n", ballance);
			}break;

			}
		} while (i != 6);

		return 0;
}

